[package]
name = "vanity_addy"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.0"
borsh = "0.10.3"
diesel = { version = "2.1.0", features = ["postgres"] }
diesel_migrations = "2.1.0"
dotenvy = "0.15"

