services:
  - type: web
    name: eoneeko-vanity
    env: python
    buildCommand: pip install -r aoos/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
    plan: free
    region: oregon
    rootDir: backend
